CLINICAL_KNOWLEDGE_BASE = [
    'Obesity', 'Artifacts', 'renal osteodystrophies', 'eventration', 'Abdomen', 
    'Enteral Nutrition', 'Scars', 'Diaphragms', 'pulmonary granuloma', 
    'calcified granuloma', 'Stomach', 'aortic atherosclerosis', 'lung disease', 
    'calcific tendinitis', 'morgagni hernia', 'Interstitial', 
    'bronchial wall thickening', 'chronic lung disease', 'large hiatal hernia', 
    'Scarring', 'Pericardial Effusion', 'traction bronchiectasis', 'Femur', 
    'osteophytes', 'Foreign Body', 'clavicular fracture', 'Pulmonary Embolism', 
    'Foreign Bodies', 'Interstitial Lung Disease', 'Bronchiectases', 
    'lower lobe pneumonia', 'degenerative arthritis', 'Peripheral Vascular Disease', 
    'collapse', 'aorta tortuous', 'Bronchitis', 'cardiac monitor', 
    'chronic obstructive lung disease', 'Vascular Calcification', 'thyroid cancer', 
    'granuloma', 'cervical fusion', 'Aorta', 'foreign body', 'hyperinflation', 
    'metastases', 'Thoracic', 'pneumonia', 'paratracheal mass', 
    'mitral annular calcification', 'Rib', 'Hiatus', 'congestive heart failure', 
    'fourth rib fracture', 'Bronchiectasis', 'Chest Tubes', 'retropulsion', 
    'apical granuloma', 'Stents', 'Sternotomy', 'Intubation', 'osteoarthritis', 
    'aortic calcifications', 'Cardiomegaly', 'hyperinflation lungs', 
    'congestive cardiac failure', 'Asbestosis', 'Dyspnea', 'Scar', 'Pleura', 
    'hemothorax', 'Dilated', 'Obstructive', 'bronchiolitides', 
    'chronic obstructive pulmonary disease', 'Venous Engorgement', 
    'superimposed infection', 'Pneumothorax', 'pulmonary artery hypertension', 
    'neoplasm', 'arthroplasties', 'pulmonary hypertension', 
    'obstructive atelectasis', 'Tracheostomy', 'Bone Density', 'Esophagectomy', 
    'Goiter', 'pleural calcification', 'Pulmonary Arteries', 'Chronic Disease', 
    'Laparoscopic Surgery', 'arthritis', 'pleural thickening', 
    'cervical spine surgeries', 'Inflammation', 'hyperexpansion of lung', 
    'generalized osteopenia', 'Pacemaker', 'Osteoporosis', 'Granuloma', 
    'Pulmonary Fibrosis', 'Intestinal Perforation', 'Subcutaneous Emphysema', 
    'Mediastinal Diseases', 'callus', 'Pulmonary Edema', 'hernias', 
    'alveolar edema', 'Lumpectomy', 'degenerative disease', 'degeneration', 
    'humeral fracture', 'cystic fibrosis', 'bochdalek hernia', 
    'displaced fractures', 'Follow-Up Studies', 'Respiratory Tract Infections', 
    'Cardiac Failure', 'chronic fibrosis', 'Pulmonary Disease', 'pleuritis', 
    'Diffuse Idiopathic Skeletal', 'obstructive pulmonary diseases', 
    'discoid atelectasis', 'hyperlucent lung', 'Central Venous Catheter', 
    'Sutures', 'right atrial enlargement', 'Pneumonectomy', 
    'interstitial fibrosis', 'Descending Aorta', 'hemorrhages', 'Heart Atria', 
    'fracture-dislocation', 'chronic interstitial lung disease', 'emphysemas', 
    'Cachexia', 'asbestos exposure', 'aortic valve replacement', 
    'pathologic fractures', 'Thoracic Spondylosis', 'scleroses', 
    'mediastinal lymphadenopathy', 'Jugular Veins', 'Catheterization', 
    'cervical spine fusion', 'Lymphadenopathy', 'diaphragm eventration', 
    'Coronary Artery Bypass', 'thoracotomies', 'air trapping', 
    'pulmonary emphysema', 'Pleural Disease', 'mastectomies', 
    'peribronchial pneumonia', 'pulmonary metastasis', 'dilation', 'Bullae', 
    'effusion', 'Dilatation', 'sarcoid', 'Severe Early-Onset', 'displacement', 
    'stabilization', 'focal atelectasis', 'Calcinosis', 'Pleural Effusions', 
    'aortic dissection', 'Hyperlucent', 'Thorax', 
    'absence of right pulmonary artery', 'nasogastric tube', 'Abdominal', 
    'Thoracic Wall', 'Superior', 'Artefact', 'Lymph Node', 'azygos lobe', 
    'infection', 'sarcoidoses', 'Aortic Aneurysm', 'Azygos Vein', 
    'Thyroid Gland', 'Mitral Valve', 'Cystic Fibrosis', 'bullous emphysema', 
    'viral bronchiolitis', 'Knee Joint', 'Scoliosis', 'lung carcinoma', 
    'colonic interposition', 'opacity', 'Photon', 'patchy atelectasis', 
    'pneumoperitoneum', 'closure', 'pneumothorax', 'left lower lobe pneumonia', 
    'Shoulder', 'obliteration', 'Lymphatic Diseases', 'Paralysis', 
    'Pulmonary Artery', 'Replacement', 'Left Atrium', 'electronic cardiac device', 
    'pulmonary fibroses', 'muscle spasm', 'Cardiovascular Diseases', 'Hemothorax', 
    'Intestinal Obstruction', 'congestion', 'cholecystectomies', 'Catheters', 
    'breast carcinoma', 'Tendinopathy', 'ventricular hypertrophy', 'amputation', 
    'Bronchiolitis', 'mid sternotomy', 'prostheses', 
    'Heart Valve Prosthesis Implantation', 'Chest Wall', 'multiple fractures', 
    'Obstructive Lung Disease', 'Sacrum', 'Knee Prosthesis', 'Gunshot', 
    'cachexia', 'cardiac failure', 'Indwelling', 'Hiatal', 'gall stone', 
    'Aortic Diseases', 'Right Atrium', 'pulmonary process', 'metastatic disease', 
    'deformity', 'Emphysema', 'rib fracture', 'kyphoses', 
    'Pulmonary arterial hypertension', 'bone demineralization', 
    'Congestive Heart Failure', 'acromioclavicular separation', 
    'small airway disease', 'hyperexpansion', 'brain tumor', 
    'bilateral hilar adenopathy', 'atheroscleroses', 'Lung Neoplasms', 
    'vertebral fracture', 'adenopathy', 'Rib Fracture', 'Contusion', 'bronchitis', 
    'obese', 'recurrent pneumonia', 'Left Ventricular', 'rotated fracture', 
    'Cardiomyopathy', 'laparoscopic surgery', 'granulomatous disease', 
    'acute pneumonia', 'Osteophyte', 'Humeral Head', 'edemas', 
    'degenerative change', 'lung hyperinflation', 'degenerative disc diseases', 
    'bypass grafts', 'multiple pulmonary nodules', 'Femoral Neck Fractures', 
    'goiter', 'Central Venous Catheters', 'cabg', 
    'diffuse idiopathic skeletal hyperostosis', 'Humerus', 'Dislocation', 
    'Intervertebral Disc Displacement', 'Pathologic', 'Vena Cava', 
    'Renal Dialysis', 'Hemopneumothorax', 'old injury', 'picc line', 
    'Pulmonary Emphysema', 'subchondral cyst', 'piercing', 'Cholecystectomy', 
    'Pleural Diseases', 'embolisation', 'gunshot wounds', 'Funnel Chest', 
    'aspergilloma', 'DISH', 'Clavicle', 'chest surgery', 'tracheostomies', 
    'arthritic changes', 'Spinal Fractures', 'Cervical Vertebrae', 
    'Postoperative Period', 'Thoracic Aorta', 'Heart Valve Prosthesis', 'empyema', 
    'Edema', 'Multiple Pulmonary Nodules', 'granulomatous infection', 
    'Pneumonitis', 'Chronic Granulomatous Disease', 'scaphoid abdomen', 
    'In-Dwelling Catheter', 'sternotomy', 'Cicatrix', 'bilateral breast implants', 
    'Hiatal Hernia', 'Spinal Osteophytosis', 'biliary stents', 'dissection', 
    'Brain Tumor', 'Neck', 'lung cancer', 'fusion', 'Tuberculosis', 'Clip', 
    'Viral', 'atherosclerotic vascular disease', 'abdominal surgery', 
    'left-sided pleural effusion', 'obstructive lung disease', 
    'prosthetic right shoulder', 'pectus carinatum', 'hiatal hernia', 
    'surgical resection', 'Central Venous', 'Thoracotomy', 'Intratracheal', 
    'Histoplasmosis', 'Fractures', 'fibroses', 'Peripheral', 'Fracture Healing', 
    'neoplastic processes', 'left ventricular enlargement', 'Diaphragm', 
    'Enlarged Heart', 'Humeral Fracture', 'Osteopenia', 'Exostoses', 
    'Pleural Effusion', 'postobstructive pneumonia', 'Hypertrophy', 
    'Cholelithiasis', 'bilateral pleural effusion', 'Intervertebral Disc', 
    'calcified lymph nodes', 'pleural effusions', 'Mucus', 
    'right upper lobe pneumonia', 'Surgical Clip', 'lumpectomy', 'obstruction', 
    'fusion procedure', 'Stent', 'pneumatocele', 'interstitial pulmonary edema', 
    'Gastrointestinal', 'Mammaplasty', 'Pulmonary Hypertension', 
    'colonic perforation', 'Callus', 'Joint Prosthesis', 'overlapping structures', 
    'Ascending Aorta', 'subcutaneous emphysema', 'Pectus Excavatum', 'Spine', 
    'Rib Fractures', 'Pyriform Sinus', 'Pain', 'hematomas', 'surgery', 
    'Chronic Obstructive Lung Disease', 'breast implants', 'Neoplasm', 
    'pancreatitis', 'central venous catheters', 'Vertebroplasty', 'picc', 
    'thoracolumbar scoliosis', 'Dextrocardia', 'pleural plaque', 
    'Thyroid Cancer', 'Intervertebral Disc Degeneration', 'venous engorgement', 
    'tortuous aorta', 'Lungs', 'Subclavian Vein', 'Lumbar Vertebrae', 
    'dextrocardia', 'plate-like atelectasis', 'Lymph Nodes', 'contusion', 
    'Adipose Tissue', 'Large', 'Heart Failure', 'Cardiopulmonary Bypass', 
    'Spinal Injuries', 'Pulmonary Atelectasis', 'interstitial lung disease', 
    'lumbar spine fusion', 'retraction', 'Bone', 'internal fixation', 
    'Spondylarthritis', 'Vascular Diseases', 'cardiothoracic ratio', 
    'pneumonia right lower lobe', 'multiple myeloma', 'dilated cardiomyopathies', 
    'Morbid', 'Axilla', 'lobectomy', 'Osteoarthritis', 
    'anterior mediastinal masses', 'Pulmonary', 'Bronchi', 'Aortic Valve', 
    'Hernia', 'chest infection', 'tuberculoses', 'hypoventilation', 'Ectasia', 
    'volume overload', 'stable fracture', 'Centrilobular Emphysema', 
    'Middle Lobe Syndrome', 'Knee', 'left upper lobe pneumonia', 'Gallstones', 
    'pleural fluid', 'atelectases', 'Aneurysm', 'Catheter', 'Bone Anchor', 
    'ectasia', 'interstitial disease', 'pulmonary edema', 'Pleuritis', 
    'multilobar pneumonia', 'mass lesion', 'calcifications of the aorta', 
    'Osteophytes', 'bone island', 'degenerative joint disease', 'Diaphragmatic', 
    'pericardial effusion', 'Heart Ventricles', 'histoplasmoses', 
    'esophagectomies', 'Granulomatous Disease', 'small bowel obstruction', 
    'scolioses', 'diffuse fibrosis', 'Right Ventricle', 'Fracture', 
    'Hydropneumothorax', 'Opportunistic Infection', 'osteopenia', 'tips', 
    'right-sided pleural effusion', 'osteoporoses', 'chronic atelectasis', 
    'vertebroplasty', 'chronic edema', 'Respiratory Tract Diseases', 
    'Hip Fractures', 'spondylosis', 'lung surgeries', 'Dissecting', 
    'Breast Carcinoma', 'pectus excavatum', 'in dwelling catheters', 
    'Spondylosis', 'spine curvature', 'Esophagus', 'Vascular Calcifications', 
    'Torso', 'enchondroma', 'Granulomas', 'Wounds', 'cholelithiases', 
    'Arthritis', 'pulmonary arterial hypertension', 'pneumonitis', 'Chronic', 
    'heart failure', 'Pancreatitis', 'lung granuloma', 'coronary bypass', 
    'cervical spinal fusion', 'anchors', 'Fibrosis', 'non-displaced fracture', 
    'Hyperostosis', 'Spinal Fusion', 'Trachea', 'lung consolidation', 
    'Pneumonia', 'Atherosclerosis', 'nodule', 'ascending aortic aneurysm', 
    'atypical pneumonias', 'post traumatic deformity', 'dyspnea', 
    'Absorptiometry', 'Pulmonary Aspergillosis', 'chronic granulomatous disease', 
    'mitral valve replacement', 'pulmonary sarcoidosis', 
    'peripheral vascular disease', 'arterial abnormality', 
    'vascular calcification', 'Coronary Vessels', 'fracture', 'Arthroplasty', 
    'scarring', 'Lung Cancer', 'aneurysms', 'Lung Volume Reduction', 'Artificial', 
    'scar', 'Intestine', 'hilar calcification', 'Hypertension', 'skin fold', 
    'Esophagogastric Junction', 'Pulmonary Valve', 'demineralization', 
    'Chronic Obstructive', 'hemopneumothorax', 'myocardial revascularization', 
    'Multiple Myeloma', 'Atelectasis', 'Kyphosis', 'copd', 'Pneumoperitoneum', 
    'aortic disease', 'venous hypertension', 'infiltrates', 'hiatus hernia', 
    'Lymph', 'cavitation', 'Lumbosacral Region', 'chronic pulmonary embolism', 
    'Thoracic Vertebrae', 'cervical arthritis', 'thoracic spondylosis', 
    'Lung Diseases', 'malignancy', 'Ribs', 'dialysis', 'spine injury', 
    'spinal fusion', 'Sternum', 'Exudates and Transudates', 'thyroid mass', 
    'bronchiectases', 'Drainage', 'Small', 'hilar adenopathy', 'sclerotic', 
    'Humeral Fractures', 'right lower lobe pneumonia', 'bulla', 'Kidney', 
    'opportunistic infection', 'left atrial enlargement', 
    'interstitial pneumonitides', 'Shoulder Dislocation', 'aortic ectasia', 
    'aspiration', 'Sarcoidosis', 'centrilobular emphysema'
]